# Generated by Django 5.2.8 on 2025-11-28 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('department', models.CharField(choices=[('general', 'General Dentistry'), ('orthodontics', 'Orthodontics'), ('periodontics', 'Periodontics'), ('endodontics', 'Endodontics'), ('oral_surgery', 'Oral Surgery'), ('pediatric', 'Pediatric Dentistry')], default='general', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Tariffs',
                'ordering': ['department', 'act_name'],
            },
        ),
    ]
