# Generated by Django 5.1 on 2025-12-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='insurance_membership_number',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('outpatient', 'Outpatient'), ('inpatient', 'Inpatient')], default='outpatient', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='membership_number',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
