# Generated by Django 5.1 on 2025-12-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_invoice_insurance_membership_number_invoice_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='insurance_membership_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='insurance',
        ),
        migrations.AddField(
            model_name='invoice',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='cell',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='district',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurer',
            field=models.CharField(blank=True, choices=[('RSSB', 'RSSB'), ('RAMA', 'RAMA'), ('MMI', 'MMI'), ('SANLAM', 'SANLAM'), ('BRITAM', 'BRITAM'), ('OLDMUTUAL', 'OLDMUTUAL'), ('PRIME', 'PRIME'), ('RADIANT', 'RADIANT'), ('MISUR', 'MIS/UR'), ('EDENCARE', 'EDENCARE'), ('OTHER', 'Other')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurer_other',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='nationality',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='occupation',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='parent_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='province',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='religion',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='sector',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='village',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
