# Generated by Django 5.1 on 2025-12-07 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_clinicuser_phone_clinicuser_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='HMISClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MedicalCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('fitness', 'Certificate of Fitness'), ('sick_leave', 'Sick Leave'), ('medical_report', 'Medical Report'), ('referral', 'Referral Letter'), ('other', 'Other')], max_length=50)),
                ('diagnosis', models.TextField()),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('duration_days', models.IntegerField(blank=True, help_text='Duration for sick leave', null=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('printed', models.BooleanField(default=False)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.clinicuser')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.patient')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='clinic.visit')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chief_complaint', models.TextField(blank=True, help_text='Main reason for visit', null=True)),
                ('history_presenting_illness', models.TextField(blank=True, help_text='Detailed history of current condition', null=True)),
                ('past_medical_history', models.TextField(blank=True, help_text='Previous medical conditions, surgeries, hospitalizations', null=True)),
                ('past_dental_history', models.TextField(blank=True, help_text='Previous dental treatments, procedures', null=True)),
                ('current_medications', models.TextField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('social_history', models.TextField(blank=True, help_text='Smoking, alcohol, occupation, lifestyle', null=True)),
                ('family_history', models.TextField(blank=True, help_text='Family medical/dental conditions', null=True)),
                ('review_of_systems', models.TextField(blank=True, help_text='Systematic review of body systems', null=True)),
                ('general_examination', models.TextField(blank=True, help_text='General appearance, vital signs, overall health', null=True)),
                ('oral_examination', models.TextField(blank=True, help_text='Oral cavity examination findings', null=True)),
                ('specialty_examination', models.TextField(blank=True, help_text='Detailed specialty-specific findings', null=True)),
                ('investigations', models.TextField(blank=True, help_text='Lab results, radiograph findings', null=True)),
                ('diagnosis', models.TextField(blank=True, help_text='Clinical diagnosis', null=True)),
                ('treatment_plan', models.TextField(blank=True, help_text='Proposed treatment and management', null=True)),
                ('hmis_classification', models.CharField(blank=True, help_text='HMIS disease code', max_length=10, null=True)),
                ('idsr_disease', models.CharField(blank=True, choices=[('AFP', 'Acute Flaccid Paralysis'), ('MEASLES', 'Measles'), ('NEONATAL_TETANUS', 'Neonatal Tetanus'), ('YELLOW_FEVER', 'Yellow Fever'), ('VIRAL_HEMORRHAGIC', 'Viral Hemorrhagic Fever'), ('CHOLERA', 'Cholera'), ('MENINGITIS', 'Meningitis'), ('RABIES', 'Rabies'), ('ANTHRAX', 'Anthrax'), ('PLAGUE', 'Plague'), ('TYPHOID', 'Typhoid Fever'), ('MALARIA', 'Malaria'), ('HIV', 'HIV/AIDS'), ('TB', 'Tuberculosis'), ('COVID19', 'COVID-19'), ('MPOX', 'Mpox'), ('OTHER', 'Other')], max_length=100, null=True)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='clinic.visit')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecordAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='medical_records/%Y/%m/')),
                ('file_type', models.CharField(choices=[('photo', 'Photo'), ('xray', 'X-Ray'), ('lab_result', 'Lab Result'), ('document', 'Document'), ('other', 'Other')], max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='clinic.medicalrecord')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.clinicuser')),
            ],
        ),
        migrations.CreateModel(
            name='PatientTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('transferred_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('from_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='clinic.department')),
                ('from_doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='clinic.clinicuser')),
                ('to_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to='clinic.department')),
                ('to_doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to='clinic.clinicuser')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='clinic.visit')),
            ],
        ),
    ]
