# Generated by Django 5.1 on 2025-12-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0012_notificationlog_alter_prescription_visit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingitem',
            name='notes',
            field=models.TextField(blank=True, help_text='Details to appear on the invoice.', null=True),
        ),
    ]
