# Generated by Django 5.1 on 2025-12-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0015_inventoryitem_category_inventoryitem_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitem',
            name='dosage',
            field=models.CharField(blank=True, help_text='e.g., 250mg, 1 tablet', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='duration',
            field=models.CharField(blank=True, help_text='e.g., 7 days', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='frequency',
            field=models.CharField(blank=True, help_text='e.g., 3 times daily', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='instructions',
            field=models.TextField(blank=True, help_text='Additional instructions', null=True),
        ),
    ]
