from django.urls import path
from .views_reception import (
    reception_login,
    reception_dashboard,
    reception_register_patient,
    reception_patient_list,
    reception_appointments_today,
    reception_patients,
    reception_check_in,
    today_appointments,
    patient_detail,
    send_patient_to_doctor,
    edit_appointment,
    cancel_appointment,
    patient_profile,
    reception_profile,
    reception_update_profile,
    reception_update_profile_picture,
    queue_call_patient,
    queue_update_status,
)
from . import views_dashboards
from . import views_patient_workflow

urlpatterns = [
    path('login/', reception_login, name='reception_login'),
    path('', reception_dashboard, name='reception_dashboard'),
    path('create-visit/', views_patient_workflow.reception_create_visit, name='reception_create_visit'),
    path('register/', reception_register_patient, name='reception_register_patient'),
    path('patients/', reception_patient_list, name='reception_patient_list'),
    path('patient/<int:patient_id>/', patient_detail, name='patient_detail'),
    path('patient/<int:patient_id>/profile/', patient_profile, name='patient_profile'),
    path('patient/<int:patient_id>/send-to-doctor/', send_patient_to_doctor, name='send_patient_to_doctor'),
    path('appointments/today/', reception_appointments_today, name='reception_appointments_today'),
    path('patients/search/', reception_patients, name='reception_patients'),
    path('today/appointments/', today_appointments, name='reception_today_appointments'),
    path('appointments/checkin/<int:appointment_id>/', reception_check_in, name='reception_check_in'),
    path('appointments/<int:appointment_id>/edit/', edit_appointment, name='reception_edit_appointment'),
    path('appointments/<int:appointment_id>/cancel/', cancel_appointment, name='reception_cancel_appointment'),
    path('schedule/', views_dashboards.reception_schedule_appointment_form, name='reception_schedule_appointment_form'),
    path('schedule/save/', views_dashboards.reception_schedule_appointment, name='reception_schedule_appointment'),
    path('schedule/get-doctors/', views_dashboards.get_doctors_by_department, name='get_doctors_by_department'),
    path('appointments/', views_dashboards.reception_appointments, name='reception_appointments'),
    path('appointments/<int:appointment_id>/confirmation/', views_dashboards.reception_appointment_confirmation, name='reception_appointment_confirmation'),
    path('appointments/<int:appointment_id>/print/', views_dashboards.print_appointment, name='print_appointment'),
    path('profile/', reception_profile, name='reception_profile'),
    path('profile/update/', reception_update_profile, name='reception_update_profile'),
    path('profile/picture/', reception_update_profile_picture, name='reception_update_profile_picture'),
    path('queue/<int:queue_id>/call/', queue_call_patient, name='queue_call_patient'),
    path('queue/<int:queue_id>/update/', queue_update_status, name='queue_update_status'),
]
