# Generated by Django 5.2.8 on 2025-11-28 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('insurance_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('department', models.CharField(choices=[('general', 'General Dentistry'), ('orthodontics', 'Orthodontics'), ('periodontics', 'Periodontics'), ('endodontics', 'Endodontics'), ('oral_surgery', 'Oral Surgery'), ('pediatric', 'Pediatric Dentistry')], default='general', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
